### ISSUE TITLE
Ship v2.0.1 as v3.0.0

### ISSUE THREAD

**Issue by mcollina** [isaacs/bind-obj-methods#4]
Hi @isaacs,

The v2.0.1 update broke a few pipelines that still tested on Node.js v6. Could you restore v2.0.0 as latest and ship v2.0.1 as v3.0.0? Thanks!

**Comment by isaacs** [comment]
Reverted as 2.0.2, published as 3.0.1.

**Comment by mcollina** [comment]
Thanks!
